development:
  adapter: mysql2
  encoding: utf8
  database: survey_system
  username: root
  password: MyDb97.11

test:
  adapter: mysql2
  encoding: utf8
  database: test_db
  username: root
  password: MyDb97.11