# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6360c4ad0e3b145e6ec4a44de1bca73ee0e26ac8671dda30f82d513ab287bfbde7eaa63571efcd17867b6b4363d4cc7b1ff0c5c350d39edd2996f96050d6415f

test:
  secret_key_base: e165bed4a88bd5db397abb1fb58aae27fa75286500913b267a6b0cdeda20ae5f6e8908cd8bc9fc93be5ec4bf74754fab42e59b4de3861979b72ef8bd06e4e8fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
